#1175 - initial unloadedmodules plugin
volatilityfoundation/volatility3 pull request #1176
Opened 2024-06-21 13:33 UTC by superponible

This adds the missing volatility2 plugin unloadedmodules

<pre>
$ python vol.py -f data.lime windows.unloadedmodules.UnloadedModules
Name	StartAddress	EndAddress	Time

sacdrv.sys	0xfffff8057eaf0000	0xfffff8057eb0f000	2024-06-14 06:10:25.000000
hwpolicy.sys	0xfffff8057fc80000	0xfffff8057fc91000	2024-06-14 06:10:29.000000
WdBoot.sys	0xfffff8057ea10000	0xfffff8057ea1c000	2024-06-14 06:10:29.000000
KMPDC.sys	0xfffff805824f0000	0xfffff805824ff000	2024-06-14 06:10:31.000000
dam.sys	0xfffff805824d0000	0xfffff805824ec000	2024-06-14 06:10:31.000000
dump_stornvme.sys	0xfffff80580380000	0xfffff805803b7000	2024-06-14 06:10:34.000000
dump_storport.sys	0xfffff80580330000	0xfffff80580340000	2024-06-14 06:10:34.000000
WdmCompanionFilter.sys	0xfffff80582e90000	0xfffff80582e9c000	2024-06-14 06:10:40.000000
MSKSSRV.sys	0xfffff80579d10000	0xfffff80579d22000	2024-06-14 06:11:13.000000
MSKSSRV.sys	0xfffff80579da0000	0xfffff80579db2000	2024-06-14 15:57:22.000000
monitor.sys	0xfffff80579400000	0xfffff8057941c000	2024-06-14 15:57:33.000000
monitor.sys	0xfffff80579dc0000	0xfffff80579ddc000	2024-06-14 16:04:05.000000
</pre>

2024-06-23 10:59 UTC, ikelos reviewed
Yep, looks good, just a slight thing about keeping the configuration tree slightly cleaner, but not a show stopper!  Just lemme know when you're happy for it to be merged.  5:)

2024-06-23 10:59 UTC, ikelos commented on volatility3/framework/plugins/windows/unloadedmodules.py
> +            config_path,
So, I'd take `config_path` and append a specific value to it (using `config.path_join`) to keep the values together and not muddy the config path you've already provided.  Otherwise it's like dumping everything under HKLM/Software/Microsoft directly into that key!  It'll just help name collision avoidance.

2024-06-23 10:59 UTC, ikelos commented on volatility3/framework/plugins/windows/unloadedmodules.py
> +    def generate_timeline(self):
Good work adding timeliner support, thanks!  5:D

2024-06-23 11:08 UTC, ikelos approved these changes
Looks good!  Thanks!  5:D

2024-07-14 17:24 UTC, ikelos requested changes
Sorry, happy to get this pushed, but the config_path should really have an additional value attached to it.  Sorry for marking it approved initially...

2024-07-15 20:27 UTC, superponible commented on volatility3/framework/plugins/windows/unloadedmodules.py
> +            config_path,
@ikelos not totally sure I follow so wanted to confirm. I saw another plugin with this

<pre>
./volatility3/framework/plugins/windows/poolscanner.py-                config_path=configuration.path_join(
./volatility3/framework/plugins/windows/poolscanner.py-                    context.symbol_space[symbol_table].config_path, "poolheader"
</pre>

so in this case you just mean doing something like this?

`config_path=configuration.path_join(config_path, "unloaded_modules")`

2024-07-15 20:46 UTC, superponible commented on volatility3/framework/plugins/windows/unloadedmodules.py
> +            config_path,
i pushed a commit based on that assumption, so if it's right, this should be good.

2024-07-16 21:51 UTC, ikelos approved these changes
Yep, that's exactly right, thanks!  5:)

2024-07-16 21:51 UTC, merged